### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by yangwang** [XiaoGerGer/zimuzu-yyets-resourcelist#4]
参考以下脚本，如果可以把人人的分级条目添加进豆瓣就好了
[Douban Download Search（支持https）](https://greasyfork.org/zh-CN/scripts/36067-douban-download-search-%E6%94%AF%E6%8C%81https)
[豆瓣资源下载大师](https://greasyfork.org/nl/scripts/329484-%E8%B1%86%E7%93%A3%E8%B5%84%E6%BA%90%E4%B8%8B%E8%BD%BD%E5%A4%A7%E5%B8%88-1%E7%A7%92%E6%90%9E%E5%AE%9A%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1-%E9%9F%B3%E4%B9%90-%E5%9B%BE%E4%B9%A6%E4%B8%8B%E8%BD%BD)

**Comment by XiaoGerGer** [comment]
能描述得详细点吗，我没有用过豆瓣

**Comment by MartialArtist** [comment]
是这样的，不方便放图，就用文字说明吧。在豆瓣打开一部电影，有许多条目，比如导演、编剧、主演等。就是缺少个分级条目，我上面说的脚步就可以添加一个下载资源的条目，比如直接链接到人人影视相应电影的详情页。我的意思是你整理的数据如果能够匹配并以脚步或插件的形式在相应的豆瓣电影形成一个分级的条目，就更好了。
